import Head from "next/head";
import Header from "../components/header/header";
import Main from "../components/main/main";
import Footer from "../components/footer/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Language Cloud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Main />
      <Footer />
    </div>
  );
}

export async function getStaticProps(context) {
  return {
    props: {}, // will be passed to the page component as props
  };
}
